-- Phase 4 report engine tables. Three tables:
--   reports          — one row per generated report
--   usage_events     — fine-grained LLM call accounting (cost ceiling enforcement)
--   chunk_retrievals — which library chunks fed which report (library-health metrics)
--
-- All three are service-role only. The Edge Function (invoke-llm + the report
-- generator) uses the service role; users read their own reports through a
-- separate SELECT policy on `reports`.

-- ─── reports ────────────────────────────────────────────────────────────────

create table public.reports (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid references auth.users(id) on delete set null,

  -- The chart fingerprint (birth_date / birth_time / timezone / lat / long),
  -- so two reports for the same chart can share retrieval cache later. Nullable
  -- because Phase 4 iteration uses ad-hoc chart inputs without a stored chart row.
  chart_id        uuid,
  chart_input     jsonb,

  -- "Foundation Report" | "Planetary Overview" | "Composite" (Phase 6)
  kind            text not null default 'foundation',
  -- "short" | "standard" | "long" (master plan tiers)
  length          text not null default 'standard',

  -- "pending" | "running" | "ready" | "failed" | "flagged"
  status          text not null default 'pending',
  failure_reason  text,

  -- Body content. Markdown is the canonical format; PDF/audio are derived.
  body_md         text,
  audio_url       text,
  pdf_url         text,

  -- Aggregate cost across all LLM calls for this report (sum of usage_events).
  cost_cents      int default 0,

  -- Traceability. fingerprint includes: model used, prompt version, sha256 of
  -- system prompt, list of chunk ids referenced, library snapshot timestamp,
  -- chart fingerprint hash.
  fingerprint     jsonb not null default '{}',

  created_at      timestamptz not null default now(),
  completed_at    timestamptz
);

create index reports_user_idx on public.reports (user_id) where user_id is not null;
create index reports_status_idx on public.reports (status);
create index reports_created_at_idx on public.reports (created_at desc);

alter table public.reports enable row level security;

-- Users read only their own reports. Service role bypasses RLS for writes.
create policy "users can read own reports"
  on public.reports
  for select
  to authenticated
  using (auth.uid() = user_id);

-- ─── usage_events ───────────────────────────────────────────────────────────

create table public.usage_events (
  id              bigint generated by default as identity primary key,
  user_id         uuid references auth.users(id) on delete set null,
  report_id       uuid references public.reports(id) on delete set null,

  -- "report.generate" | "transit.daily" | "embed" | "alert.cost_ceiling" | ...
  kind            text not null,
  -- "claude-sonnet-4-6" | "claude-haiku-4-5" | "text-embedding-3-small" | ...
  model           text,

  input_tokens            int default 0,
  output_tokens           int default 0,
  cache_read_input_tokens int default 0,
  cache_write_input_tokens int default 0,

  -- Computed cost (integer cents). For ceiling enforcement and rollups.
  cost_cents      int default 0,

  -- Free-form context. Useful for alert rows (model + projected cost), for
  -- correlating retries, etc.
  meta            jsonb not null default '{}',

  created_at      timestamptz not null default now()
);

create index usage_events_report_idx on public.usage_events (report_id) where report_id is not null;
create index usage_events_user_idx on public.usage_events (user_id) where user_id is not null;
create index usage_events_kind_idx on public.usage_events (kind);
create index usage_events_created_at_idx on public.usage_events (created_at desc);

alter table public.usage_events enable row level security;
-- No policy = service-role-only. Users never see raw usage rows; they get cost
-- summaries through the reports.cost_cents column.

-- ─── chunk_retrievals ───────────────────────────────────────────────────────

create table public.chunk_retrievals (
  id              bigint generated by default as identity primary key,
  chunk_id        uuid references public.chunks(id) on delete cascade,
  report_id       uuid references public.reports(id) on delete cascade,

  -- Position in the retrieval ranking (1 = top hit). Lets us audit retrieval
  -- quality: if rank 12 chunks are rarely cited in the final report, drop the
  -- top_k limit. Phase 3.5 / 4 metric.
  rank            int,
  similarity      float,

  retrieved_at    timestamptz not null default now()
);

create index chunk_retrievals_chunk_idx on public.chunk_retrievals (chunk_id);
create index chunk_retrievals_report_idx on public.chunk_retrievals (report_id);
create index chunk_retrievals_retrieved_idx on public.chunk_retrievals (retrieved_at desc);

alter table public.chunk_retrievals enable row level security;
-- Service-role only. Powers the library-health endpoint (never-retrieved chunks,
-- retrieval-rank distributions) which already runs as service-role.

-- ─── trigger: touch reports.completed_at when status becomes ready/failed ───

create or replace function public.touch_report_completed()
returns trigger
language plpgsql
as $$
begin
  if new.status in ('ready', 'failed') and old.status not in ('ready', 'failed') then
    new.completed_at = now();
  end if;
  return new;
end;
$$;

create trigger reports_touch_completed
  before update on public.reports
  for each row execute function public.touch_report_completed();
